---
#ansible-playbook ansible_lrg_playbook.yaml -i ansible_lrg_inventory.yaml
#
#Eventually:
#ansible-playbook ansible_lrg_playbook.yaml -i ansible_lrg_inventory.yaml --ask-vault-pass

- hosts: localhost
  gather_facts: no
  tasks:

    - name: Template the Things
      template:
          dest: ./output/resume.md # required. Location to render the template to on the remote machine.
          src: ./templates/{{template_file}} # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.
    